services:
    kernel.listener.warden_exception_listener:
        class: Deeson\WardenBundle\Listener\ExceptionListener
        arguments: [@templating, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    user_provider:
        class: Deeson\WardenBundle\Services\UserProviderService
        arguments: [%kernel.root_dir%]

    warden_setup:
        class: Deeson\WardenBundle\Services\WardenSetupService
        arguments: [%kernel.root_dir%]

    warden.http_client:
        class: Deeson\WardenBundle\Client\GuzzleHttpRequestHandler

    warden.mail_manager:
        class: Deeson\WardenBundle\Services\MailService
        arguments: ['@mailer', '@twig']

    warden.ssl_encryption:
        class: Deeson\WardenBundle\Services\SSLEncryptionService
        arguments: [%public_key_file%, %private_key_file%]

    warden.site_connection:
        class: Deeson\WardenBundle\Services\SiteConnectionService
        arguments: ['@warden.http_client', '@warden.ssl_encryption', '@monolog.logger']

    warden.drupal.module_manager:
        class: Deeson\WardenBundle\Managers\ModuleManager
        arguments: ['@doctrine_mongodb', '@monolog.logger']

    warden.site_manager:
        class: Deeson\WardenBundle\Managers\SiteManager
        arguments: ['@doctrine_mongodb', '@monolog.logger']

    warden.drupal.site:
        class: Deeson\WardenBundle\Services\DrupalSiteService
        arguments: ['@warden.drupal.module_manager', '@warden.site_connection', '@monolog.logger', '@event_dispatcher']
        tags:
            - { name: kernel.event_listener, event: warden.site.update, method: onWardenSiteUpdate }
            - { name: kernel.event_listener, event: warden.site.refresh, method: onWardenSiteRefresh }
            - { name: kernel.event_listener, event: warden.site.show, method: onWardenSiteShow }
            - { name: kernel.event_listener, event: warden.cron, method: onWardenCron, priority: 100 }

    warden.drupal.module_service:
        class: Deeson\WardenBundle\Services\DrupalModuleService
        arguments: ['@warden.drupal.module_manager', '@warden.site_manager', '@monolog.logger']
        tags:
            - { name: kernel.event_listener, event: warden.cron, method: onWardenCron, priority: 30 }

    warden.drupal.module_version:
        class: Deeson\WardenBundle\Services\DrupalUpdateRequestService
        arguments: ['@warden.http_client', '@warden.site_manager', '@warden.drupal.module_manager', '@monolog.logger']
        tags:
            - { name: kernel.event_listener, event: warden.cron, method: onWardenCron, priority: 60 }

    warden.dashboard_manager:
        class: Deeson\WardenBundle\Managers\DashboardManager
        arguments: ['@doctrine_mongodb', '@monolog.logger', '@warden.site_manager', '@warden.mail_manager', '@service_container']
        tags:
            - { name: kernel.event_listener, event: warden.dashboard.update, method: onWardenDashboardUpdate }
            - { name: kernel.event_listener, event: warden.cron, method: onWardenCron, priority: -100 }
